name: On OCA Issue Created

on:
  issues:
    types:
    - opened

jobs:
  labelling_messaging:
    name: 'Add a label on creation: oca-issue then send a message to Slack'

    runs-on: ubuntu-latest

    steps:
    - name: Get event payload
      shell: pwsh
      run: |
        Write-Host '${{ toJSON(github.event) }}'

    # - name: Get checkpoints
    #   id: checkpoint
    #   shell: pwsh
    #   run: |
    #     $isOcaParticipant = "${{ contains(secrets.OCA_PARTICIPANTS, github.event.issue.user.login) }}"

    #     echo "::set-output name=isOcaParticipant::$isOcaParticipant"

    # - name: Add a label
    #   if: ${{ steps.checkpoint.outputs.isOcaParticipant == 'true' }}
    #   uses: buildsville/add-remove-label@v1
    #   with:
    #     token: "${{ secrets.GITHUB_TOKEN }}"
    #     label: 'oca-issue'
    #     type: add

    # - name: Send a message to Slack
    #   if: ${{ steps.checkpoint.outputs.isOcaParticipant == 'true' }}
    #   shell: pwsh
    #   run: |
    #     $url = "${{ secrets.OCA_SLACK_WEBHOOK_URL }}"
    #     $iconUrl = "${{ secrets.OCA_SLACK_WEBHOOK_ICON_URL }}"
    #     $channel = "${{ secrets.OCA_SLACK_CHANNEL }}"
    #     $text = "New Issue #${{ github.event.issue.number }} has been created! 👉 <${{ github.event.issue.html_url }}|View Issue>"
    #     $body = @{ "channel" = $channel; "username" = "AzFuncOpenApiBot"; "icon_url" = $iconUrl; "text" = $text; }

    #     Invoke-RestMethod -Method Post -Uri $url -Body $($body | ConvertTo-Json)
